### ISSUE TITLE
Small Problem with the Menu for the First Room

### ISSUE THREAD

**Issue by DThumma** [TRianR/RostenbachBuehler_CSCI2270_FinalProject#1]
When you go into the very starting room the menu comes up as:
1. Search Room
2. Leave Room
3. Sow player status 
4. Take Potion
5. Quit
So it shows the option "Take potion" before you have even found the potion. How you find the potion is to press 1 to search room. So it would be nice to have the menu be just:
1. Search Room
2. Leave Room
3. Sow player status 
4. Quit
until the user has already pressed 1 (searched the room).
Not really an issue just a possible improvement!

**Comment by TRianR** [comment]
We made it so the user starts the game with 3 potions already. But changing the menu to the just one you listed is a good idea for when the numPotions = 0 instead of it just cout-ing "You have no potions left".. Thanks for the input! Let us know if you find anything else or something that needs improving!

**Comment by DThumma** [comment]
Ohhhh okay I see sorry I didn't catch that!!
